woca/models/Workshop.php
<?php

namespace backend\modules\woca\models;

use Yii;

use common\behaviors\TimestampBehavior;
use common\behaviors\BlameableBehavior;
use common\behaviors\DeleteBehavior;

/**
 * This is the model class for table "woca_workshop".
 *
 * @property integer $workshop_id
 * @property integer $laporan_worksop_id
 * @property string $judul_workshop
 * @property string $tanggal
 * @property string $pelaksana
 * @property integer $deleted
 * @property string $deleted_at
 * @property string $deleted_by
 * @property string $created_at
 * @property string $created_by
 * @property string $updated_at
 * @property string $updated_by
 *
 * @property WocaLaporanWorkshopFile $laporanWorksop
 */
class Workshop extends \yii\db\ActiveRecord
{

    public $files;
    /**
     * behaviour to add created_at and updatet_at field with current datetime (timestamp)
     * and created_by and updated_by field with current user id (blameable)
     */
    public function behaviors(){
        return [
            'timestamp' => [
                'class' => TimestampBehavior::className(),
            ],
            'blameable' => [
                'class' => BlameableBehavior::className(),
            ],
            'delete' => [
                'class' => DeleteBehavior::className(),
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'woca_workshop';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['judul_workshop','tanggal_mulai','tanggal_berakhir','pelaksana','pembicara'],'required'],
            [['laporan_workshop_id', 'deleted'], 'integer'],
            [['tanggal_mulai','tanggal_berakhir', 'deleted_at', 'created_at', 'updated_at'], 'safe'],
            [['files'], 'file'],
            [['files'], 'required', 'on'=>['create']],
            [['tanggal_berakhir'],'isValid'],
            [['judul_workshop', 'pelaksana','pembicara', 'deleted_by', 'created_by', 'updated_by'], 'string', 'max' => 32], 
            [['laporan_workshop_id'], 'exist', 'skipOnError' => true, 'targetClass' => LaporanWorkshopFile::className(), 
            'targetAttribute' => ['laporan_workshop_id' => 'laporan_workshop_id']],

        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'workshop_id' => 'Workshop ID',
            'laporan_workshop_id' => 'Laporan Worksop ID',
            'judul_workshop' => 'Judul Workshop',
            'tanggal_mulai' => 'Tanggal Mulai',
            'tanggal_berakhir' => 'Tanggal Berakhir',
            'status_kegiatan_id' => 'Status Workshop Id',
            'pelaksana' => 'Pelaksana',
            'pembicara' => 'pembicara',
            'files' => 'File',
            'deleted' => 'Deleted',
            'deleted_at' => 'Deleted At',
            'deleted_by' => 'Deleted By',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
            'updated_at' => 'Updated At',
            'updated_by' => 'Updated By',
        ];
    }


        public function isValid($attribute, $params)
    {
        if(strtotime($this->tanggal_mulai)>=strtotime($this->tanggal_berakhir))
            $this->addError($attribute, 'Tidak boleh lebih awal atau sama dengan Tanggal Mulai workshop !');
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLaporanWorkshopFile()
    {
        return $this->hasOne(LaporanWorkshopFile::className(), ['laporan_workshop_id' => 'laporan_workshop_id']);
    }

    public function getStatusKegiatan()
    {
        return $this->hasOne(StatusKegiatan::className(), ['status_kegiatan_id' => 'status_kegiatan_id']);
    }
}

woca/controllers/WorkshopController.php
<?php

namespace backend\modules\woca\controllers;

use Yii;
use backend\modules\woca\models\Workshop;
use backend\modules\woca\models\LaporanWorkshopFile;
use backend\modules\woca\models\search\WorkshopSearch;
use backend\modules\woca\models\search\StatusKegiatan;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use mPDF;
/**
 * WorkshopController implements the CRUD actions for Workshop model.
 */
class WorkshopController extends Controller
{
    public function behaviors()
    {
        return [
            //TODO: crud controller actions are bypassed by default, set the appropriate privilege
            // 'privilege' => [
            //      'class' => \Yii::$app->privilegeControl->getAppPrivilegeControlClass(),
            //      'skipActions' => ['*'],
            //     ],
                
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Workshop models.
     * @return mixed
     */
    public function actionIndexMahasiswa()
    {
        $searchModel = new WorkshopSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andWhere(['deleted' => 0]);
        return $this->render('IndexMahasiswa', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            //'status_kegiatan_id' => $status_workshop,
        ]);
    }
        public function actionIndexAdmin()
    {
        $searchModel = new WorkshopSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andWhere(['deleted' => 0]);
        $status_request = Yii::$app->request->get('status_kegiatan_id');
        if($status_request == 1 || $status_request == 2 || $status_request == 3){
            $params['IzinBermalamSearch']['status_kegiatan_id'] = $status_request;
        }

        return $this->render('IndexAdmin', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'status_kegiatan_id' =>  $status_request,

        ]);
    }

    /**
     * Displays a single Workshop model.
     * @param integer $id
     * @return mixed
     */
    public function actionWorkshopByMahasiswaView($id)
    {
        return $this->render('WorkshopByMahasiswaView', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionWorkshopByAdminView($id)
    {
        return $this->render('WorkshopByAdminView', [
            'model' => $this->findModel($id),
        ]);
    }

  
    /**
     * Creates a new Workshop model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionWorkshopByMahasiswaAdd()
    {
        $model = new Workshop(); 
         if ($model->load(Yii::$app->request->post())) { 
                $model->files = UploadedFile::getInstances($model, 'files');
                $modelFile = new LaporanWorkshopFile();
                if($model->files != null){ 

                        $laporan = UploadedFile::getInstance($model,'files'); 
                        $laporanname= $laporan->baseName.'.'.$laporan->getExtension();
                       
                        $fileDir = Yii::getAlias('@WorkshopFilePath').'/'.$laporanname;
                        $modelFile->lokasi_file = $fileDir;
                        $modelFile->nama_file = $laporanname; 
                        $model->save(false);                     
                       
                        $modelFile->deleted = 0;

                        if($modelFile->validate()){ 
                            $laporan->saveAs(Yii::getAlias('@WorkshopFilePath').'/'.$laporanname);
                            $modelFile->save();
                        }else{
                           print_r("Error here" );

                            $errors = $modelFile->errors;
                            print_r(array_values($errors));
                            die();
                        }
                 
                }else{
                    print_r("null" );
                }
              $model->laporan_workshop_id = $modelFile->laporan_workshop_id;
              $model->save(false);

              return $this->redirect(['workshop-by-mahasiswa-view', 'id' => $model->workshop_id]);

        } else {
            return $this->render('WorkshopByMahasiswaAdd', [
                'model' => $model,
            ]);
        }
      } 

    /**
     * Updates an existing Workshop model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
   public function actionWorkshopByMahasiswaEdit($id)
    {
        $model = $this->findModel($id);

        
        $modelLampiran = LaporanWorkshopFile::find()->where(['laporan_workshop_id' =>$model->laporan_workshop_id])->One();
      //  $modelLampiran->softDelete();
       // var_dump($modelLampiran);
        if ($model->load(Yii::$app->request->post())) {
               $model->files = UploadedFile::getInstances($model, 'files');
                 $modelFile = new LaporanWorkshopFile();
                if($model->files != null){ 

                        $laporan = UploadedFile::getInstance($model,'files'); 
                        $laporanname= $laporan->baseName.'.'.$laporan->getExtension();
                       
                        $fileDir = Yii::getAlias('@WorkshopFilePath').'/'.$laporanname;
                        $modelFile->lokasi_file = $fileDir;
                        $modelFile->nama_file = $laporanname; 
                        $model->save(false);                     
                       
                        $modelFile->deleted = 0;

                        if($modelFile->validate()){ 
                            $laporan->saveAs(Yii::getAlias('@WorkshopFilePath').'/'.$laporanname);
                            $modelFile->save();
                        }else{
                           print_r("Error here" );

                            $errors = $modelFile->errors;
                            print_r(array_values($errors));
                            die();
                        }
                 
                }else{
                    print_r("null" );
                }
              $model->laporan_workshop_id = $modelFile->laporan_workshop_id;
              $model->save(false);
          return $this->redirect(['workshop-by-mahasiswa-view', 'id' => $model->workshop_id]);

        } else {
            return $this->render('WorkshopByMahasiswaEdit', [
                'model' => $model,
                'modelLampiran' => $modelLampiran,       
             //   'files' => $file                                                       ,
            ]);
        }
    }
    /**
     * Deletes an existing Workshop model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Workshop model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Workshop the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Workshop::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

       public function actionDownloadAdmin($id){
               //
       $model = new Workshop();
      $fileworkshop = LaporanWorkshopFile::find()->where(['laporan_workshop_id' => $id])->One();
      //var_dump($fileworkshop);
      //print_r($fileworkshop->nama_file);
      $path  = Yii::getAlias('@WorkshopFilePath');
      $data  = $fileworkshop->nama_file;
      $file  = $path.'\\'.$data;

      if(file_exists($file)){
      Yii::$app->response->SendFile($file);
      }else{
          \Yii::$app->messenger->addErrorFlash("File Tidak Tersedia");
            return $this->redirect(['index-admin']);
      }       
    }
        public function actionDownloadMahasiswa($id){
      $model = new Workshop();
      $fileworkshop = LaporanWorkshopFile::find()->where(['laporan_workshop_id' => $id])->One();
      //var_dump($fileworkshop);
      //print_r($fileworkshop->nama_file);
      $path  = Yii::getAlias('@WorkshopFilePath');
      $data  = $fileworkshop->nama_file;
      $file  = $path.'\\'.$data;

      if(file_exists($file)){
      Yii::$app->response->SendFile($file);
      }else{
          \Yii::$app->messenger->addErrorFlash("File Tidak Tersedia");
            return $this->redirect(['index-mahasiswa']);
      }       
    }
 
        public function actionCancelByMahasiswa($id)
    {
         $model = $this->findModel($id);

        if ($model->status_kegiatan_id = 1) {
            $model->status_kegiatan_id = 4;
           
            $model->save();

            \Yii::$app->messenger->addSuccessFlash("Request dibatalkan");
            return $this->redirect(['index-mahasiswa']);
        } else {
            \Yii::$app->messenger->addErrorFlash("Request tidak bisa diubah bila status sudah cancel");
            return $this->render('IndexMahasiswa', [
                'model'=>$model
            ]);
        }
    }
    
    public function actionApproveByAdminIndex($workshop){
        $model = $this->findModel($workshop);

        if($model->status_kegiatan_id == 1){
           $model->status_kegiatan_id = 2;
           $model->save();

woca/views/workshop/IndexAdmin.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
use common\components\ToolsColumn;
use backend\modules\woca\models\LaporanWorkshopFile;

/* @var $this yii\web\View */
/* @var $searchModel backend\modules\woca\models\search\WorkshopSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Workshop';
$this->params['breadcrumbs'][] = ['label' => 'Workshop', 'url' => ['index-admin']];
$this->params['breadcrumbs'][] = $this->title;
$status_url = urldecode('IzinBermalamSearch%5Bstatus_request_id%5D');

?>

<style type="text/css">
  .CustomClass table thead {
   color:  #3c8dbc;
    }
  .marginp{
    margin-top: 20px;
    margin-bottom: 20px;
  }
    .r{
        margin-left: 450px;
    }

</style>

<div class="workshop-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p class="marginp">
      <?= Html::a('Workshop', ['workshop/index-admin'], ['class' => 'btn btn-info']) ?> &nbsp &nbsp

        <?= Html::a('Kompetisi', ['kompetisi/kompetisi-by-admin-index'], ['class' => 'btn btn-info']) ?> &nbsp &nbsp

        <?= Html::a('Prestasi', ['prestasi/prestasi-by-admin-index'], ['class' => 'btn btn-info']) ?>


        <?= Html::a('Export',['excel'], ['class' => 'btn btn-primary r'])?>
    </p>




    <?= GridView::widget([
        'dataProvider' => $dataProvider,
     //   'filterModel' => $searchModel,
        'options' => [
              'class' => 'CustomClass',
         ],
         'rowOptions' => function($model){
            if($model->status_kegiatan_id == 1){
                return ['class' => 'info'];
            } else if($model->status_kegiatan_id == 2){
                return ['class' => 'success'];
            } else if($model->status_kegiatan_id == 3){
                return ['class' => 'danger'];
            } else {
                return ['class' => 'warning'];
            }
        },
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],            
            'judul_workshop',
            'tanggal_mulai',
            'tanggal_berakhir',
            'pembicara',
            'pelaksana',
            'laporan_workshop_id'=>[
                 'label' => 'File',
                // 'value' => 'Test',
                'value' => function($model){
                    $result = null;
                    $fileworkshop = LaporanWorkshopFile::find()->where(['laporan_workshop_id' => $model->laporan_workshop_id])->all();
                    foreach($fileworkshop as $data){                   
                         $result = $data->nama_file;
                    }
                    return Html::a($result,['workshop/download-admin','id'=>$model->laporan_workshop_id]);
                    //return $result;
                },
                 'format' => 'html',
                 
             ],
            [
                'attribute' => 'status_kegiatan_id',
                'label' => 'Status Permohonan',
                'value' => function($model){
                    if($model->status_kegiatan_id == 1){
                        return "Requested";
                    }elseif($model->status_kegiatan_id == 2){
                        return "Accepted";
                    }elseif ($model->status_kegiatan_id == 3) {
                        return "Rejected";
                    }elseif($model->status_kegiatan_id == 4){
                        return "Canceled";
                    }
                },
            ],
                ['class' => 'common\components\ToolsColumn',
                'template' => '{view} {approve} {reject}',
                'header' => 'Aksi',
                'buttons' => [
                    'view' => function ($url, $model){
                        return ToolsColumn::renderCustomButton($url, $model, 'View Detail', 'fa fa-eye');
                    },
                    'reject' => function ($url, $model){
                        if ($model->status_kegiatan_id == 2 || $model->status_kegiatan_id == 3 || $model->status_kegiatan_id == 4) {
                            return "";
                        }else{
                            return ToolsColumn::renderCustomButton($url, $model, 'Reject', 'fa fa-times');
                        }
                    },
                    'approve' => function ($url, $model){
                        if ($model->status_kegiatan_id == 2 || $model->status_kegiatan_id == 3 || $model->status_kegiatan_id == 4) {
                            return "";


                        }else{
                            return ToolsColumn::renderCustomButton($url, $model, 'Approve', 'fa fa-check');
                        }
                    },
                    
                ],
                'urlCreator' => function ($action, $model, $key, $index){
               //     $pegawai = Pegawai::find()->where('deleted != 1')->andWhere(['user_id' => Yii::$app->user->identity->user_id])->one();
                    if ($action === 'view') {
                        return Url::toRoute(['workshop-by-admin-view', 'id' => $key]);
                    }else if ($action === 'approve') {
                        return Url::toRoute(['approve-by-admin-index', 'workshop' => $model->workshop_id]);
                    }else if ($action === 'del') {
                        return Url::toRoute(['del', 'id' => $key]);
                    }else if ($action === 'reject') {
                        return Url::toRoute(['reject-by-admin-index', 'workshop' => $model->workshop_id]);
                     } 
                }
            ],

        //    ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

</div>

woca/views/workshop/IndexMahasiswa.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
use common\components\ToolsColumn;
use common\helpers\LinkHelper;
use backend\modules\woca\models\LaporanWorkshopFile;


/* @var $this yii\web\View */
/* @var $searchModel backend\modules\woca\models\search\WorkshopSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Workshop';
$this->params['breadcrumbs'][] = ['label' => 'Workshop', 'url' => ['index-mahasiswa']];

 

?>
     
    
<style type="text/css">
  .CustomClass table thead {
   color:  #3c8dbc;
    }
  .marginp{
    margin-top: 20px;
    margin-bottom: 20px;
  }
  .r{
        margin-left: 450px;
    }
  .btnm{
    margin-left: 13px;
  }
</style>

<div class="workshop-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p class="marginp">
        <?= Html::a('Workshop', ['workshop/index-mahasiswa'], ['class' => 'btn btn-info']) ?> &nbsp &nbsp

        <?= Html::a('Kompetisi', ['kompetisi/kompetisi-by-mahasiswa-index'], ['class' => 'btn btn-info']) ?> &nbsp &nbsp

        <?= Html::a('Prestasi', ['prestasi/prestasi-by-mahasiswa-index'], ['class' => 'btn btn-info']) ?>

        <?= Html::a('Tambah Workshop', ['workshop/workshop-by-mahasiswa-add'], ['class' => 'btn btn-success r']) ?>

    </p>
    

    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
     //   'filterModel' => $searchModel,
        'options' => [
              'class' => 'CustomClass',
         ],
         'rowOptions' => function($model){
            if($model->status_kegiatan_id == 1){
                return ['class' => 'info'];
            } else if($model->status_kegiatan_id == 2){
                return ['class' => 'success'];
            } else if($model->status_kegiatan_id == 3){
                return ['class' => 'danger'];
            } else {
                return ['class' => 'warning'];
            }
        },
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],            
            'judul_workshop',
            'tanggal_mulai',
            'tanggal_berakhir',
            'pembicara',
            'pelaksana',
            'laporan_workshop_id'=>[
                 'label' => 'File',
                // 'value' => 'Test',
                'value' => function($model){
                    $result = null;
                    $fileworkshop = LaporanWorkshopFile::find()->where(['laporan_workshop_id' => $model->laporan_workshop_id])->all();
                    foreach($fileworkshop as $data){                   
                         $result = $data->nama_file;
                    }
                    return Html::a($result,['workshop/download-mahasiswa','id'=>$model->laporan_workshop_id]);
                    //return $result;
                },
                 'format' => 'html',
                 
             ],
            [
                'attribute' => 'status_kegiatan_id',
                'label' => 'Status Permohonan',
                'value' => function($model){
                    if($model->status_kegiatan_id == 1){
                        return "Requested";
                    }elseif($model->status_kegiatan_id == 2){
                        return "Accepted";
                    }elseif ($model->status_kegiatan_id == 3) {
                        return "Rejected";
                    }elseif($model->status_kegiatan_id == 4){
                        return "Canceled";
                    }
                },
            ],
                         ['class' => 'common\components\ToolsColumn',
                'template' => '{view} {edit} {cancel}',
                'header' => 'Aksi',
                'buttons' => [
                    'view' => function ($url, $model){
                        return ToolsColumn::renderCustomButton($url, $model, 'View Detail', 'fa fa-eye');
                    },
                    'cancel' => function ($url, $model){
                        if ($model->status_kegiatan_id == 2 || $model->status_kegiatan_id == 3 || $model->status_kegiatan_id == 4) {
                            return "";
                        }else{
                            return ToolsColumn::renderCustomButton($url, $model, 'Cancel', 'fa fa-times');
                        }
                    },
                    'edit' => function ($url, $model){
                        if ($model->status_kegiatan_id == 2 || $model->status_kegiatan_id == 3 || $model->status_kegiatan_id == 4) {
                            return "";
                        } else {
                            return ToolsColumn::renderCustomButton($url, $model, 'Edit', 'fa fa-pencil');
                        }
                    },
                     
                ],
                'urlCreator' => function ($action, $model, $key, $index){
                    if ($action === 'view') {
                        return Url::toRoute(['workshop-by-mahasiswa-view', 'id' => $key]);
                    }else if ($action === 'edit') {
                        return Url::toRoute(['workshop-by-mahasiswa-edit', 'id' => $key]);
                    }else if ($action === 'cancel') {
                        return Url::toRoute(['cancel-by-mahasiswa', 'id' => $key]);
                    }
                    // else if($action === 'download'){

                    //     return Url::toRoute(['download', 'id' => $model->laporan_workshop_id]); 
                    // }
                  }
            ],

        //    ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

</div>

woca/views/workshop/WorkshopByAdminIndex.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
use common\components\ToolsColumn;
use common\helpers\LinkHelper;
use backend\modules\woca\models\LaporanWorkshopFile;


/* @var $this yii\web\View */
/* @var $searchModel backend\modules\woca\models\search\WorkshopSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Workshop';
$this->params['breadcrumbs'][] = ['label' => 'Workshop', 'url' => ['index-mahasiswa']];
$this->params['breadcrumbs'][] = $this->title;
?>

<style type="text/css">
  .CustomClass table thead {
   color:  #3c8dbc;
    }
  .marginp{
    margin-top: 20px;
    margin-bottom: 20px;
  }
  .r{
        margin-left: 450px;
    }
  .btnm{
    margin-left: 13px;
  }
</style>

<div class="workshop-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p class="marginp">
        <?= Html::a('Workshop', ['workshop/index-admin'], ['class' => 'btn btn-info']) ?> &nbsp &nbsp

        <?= Html::a('Kompetisi', ['kompetisi/index'], ['class' => 'btn btn-info']) ?> &nbsp &nbsp

        <?= Html::a('Prestasi', ['prestasi/prestasi-by-admin-index'], ['class' => 'btn btn-info']) ?>

        <?= Html::a('Tambah Workshop', ['workshop-by-mahasiswa-add'], ['class' => 'btn btn-success r']) ?>

    </p>
    

    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
     //   'filterModel' => $searchModel,
        'options' => [
              'class' => 'CustomClass',
         ],
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],            
            'judul_workshop',
            [
                  'attribute' => 'status_kegiatan_id',
                  'label' => 'Status Permohonan',
                  'value' => 'statusWorkshop.status_workshop',
            ],
            'tanggal_mulai',
            'tanggal_berakhir',
            'pembicara',
            'pelaksana',
            'laporan_workshop_id'=>[
                 'label' => 'File',
                // 'value' => 'Test',
                'value' => function($model){
                    $result = null;
                    $fileworkshop = LaporanWorkshopFile::find()->where(['laporan_workshop_id' => $model->laporan_workshop_id])->all();
                    foreach($fileworkshop as $data){                   
                         $result = $data->nama_file;
                    }
                    return Html::a($result,['workshop/download-admin','id'=>$model->laporan_workshop_id]);
                    //return $result;
                },
                 'format' => 'html',
                 
             ],
            ['class' => 'common\components\ToolsColumn',
                'template' => '{view} {edit} {cancel}',
                'header' => 'Aksi',
                'buttons' => [
                    'view' => function ($url, $model){
                        return ToolsColumn::renderCustomButton($url, $model, 'View Detail', 'fa fa-eye');
                    },
                    'cancel' => function ($url, $model){
                        if ($model->status_kegiatan_id == 2 || $model->status_kegiatan_id == 3 || $model->status_kegiatan_id == 4) {
                            return "";
                        }else{
                            return ToolsColumn::renderCustomButton($url, $model, 'Cancel', 'fa fa-times');
                        }
                    },
                    'edit' => function ($url, $model){
                        if ($model->status_kegiatan_id == 2 || $model->status_kegiatan_id == 3 || $model->status_kegiatan_id == 4) {
                            return "";
                        } else {
                            return ToolsColumn::renderCustomButton($url, $model, 'Edit', 'fa fa-pencil');
                        }
                    },
                    // 'download' => function ($url, $model){
                    //     if ($model->status_kegiatan_id == 2) {
                    //         return ToolsColumn::renderCustomButton($url, $model, 'Print', 'fa fa-print');
                    //     } else {
                    //         return "";
                    //     }
                    // },
                     
                ],
                'urlCreator' => function ($action, $model, $key, $index){
                    if ($action === 'view') {
                        return Url::toRoute(['workshop-by-mahasiswa-view', 'id' => $key]);
                    }else if ($action === 'edit') {
                        return Url::toRoute(['workshop-by-mahasiswa-edit', 'id' => $key]);
                    }else if ($action === 'cancel') {
                        return Url::toRoute(['cancel-by-mahasiswa', 'id' => $key]);
                    }
                    // else if($action === 'download'){

                    //     return Url::toRoute(['download', 'id' => $model->laporan_workshop_id]); 
                    // }
                  }
            ],

        //    ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

</div>

woca/views/workshop/WorkshopByAdminView.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use backend\modules\woca\models\LaporanWorkshopFile;


/* @var $this yii\web\View */
/* @var $model backend\modules\woca\models\Workshop */

$this->title = $model->judul_workshop;
$this->params['breadcrumbs'][] = ['label' => 'Workshops', 'url' => ['index-admin']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="workshop-view">

    <h1><?= Html::encode($this->title) ?></h1>
    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'workshop_id',
            'judul_workshop',
            'tanggal_mulai',
            'tanggal_berakhir',
            'pembicara', 
            'pelaksana',
             [
                 'label' => 'File',
                // 'value' => 'Test',
                'value' => function($model){
                    $result = null;
                    $fileworkshop = LaporanWorkshopFile::find()->where(['laporan_workshop_id' => $model->laporan_workshop_id])->all();
                    foreach($fileworkshop as $data){                   
                         $result = $data->nama_file;
                    }
                    return Html::a($result,['workshop/download-admin','id'=>$model->laporan_workshop_id]);
                    //return $result;
                },
                 'format' => 'html',
                 
             ],

            
        ],
    ]) ?>

</div>