woca/models/Kompetisi.php
<?php

namespace backend\modules\woca\models;

use Yii;

use common\behaviors\TimestampBehavior;
use common\behaviors\BlameableBehavior;
use common\behaviors\DeleteBehavior;

/**
 * This is the model class for table "woca_kompetisi".
 *
 * @property integer $kompetisi_id
 * @property string $nama_kompetisi
 * @property string $tgl_kompetisi
 * @property integer $tingkatan_kompetisi_id
 * @property integer $jumlah_peserta
 * @property integer $deleted
 * @property string $deleted_at
 * @property string $deleted_by
 * @property string $created_at
 * @property string $created_by
 * @property string $updated_at
 * @property string $updated_by
 *
 * @property WocaPeserta[] $wocaPesertas
 * @property WocaProposalKompetisiFile[] $wocaProposalKompetisiFiles
 * @property WocaTingkatanKompetisi $wocaTingkatanKompetisi
 */
class Kompetisi extends \yii\db\ActiveRecord
{

    public $filekompetisi,$tingkatan;

    /**
     * behaviour to add created_at and updatet_at field with current datetime (timestamp)
     * and created_by and updated_by field with current user id (blameable)
     */
    public function behaviors(){
        return [
            'timestamp' => [
                'class' => TimestampBehavior::className(),
            ],
            'blameable' => [
                'class' => BlameableBehavior::className(),
            ],
            'delete' => [
                'class' => DeleteBehavior::className(),
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'woca_kompetisi';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['deleted_at', 'created_at', 'updated_at'], 'safe'],
            [['nama_kompetisi','tingkatan_kompetisi_id','tahun','penyelenggara','deskripsi'],'required'],
            [['filekompetisi'], 'file','skipOnEmpty' => true ],
            [['tingkatan_kompetisi_id', 'jumlah_peserta', 'deleted','tahun'], 'integer'],
            [['nama_kompetisi'], 'string', 'max' => 100],
            [['deskripsi'], 'string', 'max' => 300],
            [['deleted_by', 'created_by', 'updated_by','tingkatan','penyelenggara'], 'string', 'max' => 32],
            [['status_kegiatan_id'], 'exist', 'skipOnError' => true, 'targetClass' => StatusKegiatan::className(), 'targetAttribute' => ['status_kegiatan_id' => 'status_kegiatan_id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'kompetisi_id' => 'Kompetisi ID',
            'nama_kompetisi' => 'Nama Kompetisi',
            'tahun' => 'Tahun',
            'tingkatan_kompetisi_id' => 'Tingkatan Kompetisi',
            'status_kegitan_id' => 'Status Kegiatan',
            'filekompetisi' => "Proposal Kompetisi",
            'tingkatan' =>'Tingkatan Kompetisi',
            'jumlah_peserta' => 'Jumlah Peserta',
            'penyelenggara' => 'Penyelenggara',
            'deskripsi' => 'Deskripsi',
            'deleted' => 'Deleted',
            'deleted_at' => 'Deleted At',
            'deleted_by' => 'Deleted By',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
            'updated_at' => 'Updated At',
            'updated_by' => 'Updated By',
        ];
    }

    // public function valid($attribute, $params)
    // {
    //     if((strtotime($this->tgl_kompetisi) > strtotime(date('Y-m-d'))&& trim($this->tgl_kompetisi)!='') )
    //         $this->addError($attribute, 'Tanggal Kompetisi Tidak Valid !');
    // }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPesertas()
    {
        return $this->hasMany(Peserta::className(), ['kompetisi_id' => 'kompetisi_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProposalKompetisiFiles()
    {
        return $this->hasMany(ProposalKompetisiFile::className(), ['kompetisi_id' => 'kompetisi_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTingkatanKompetisi()
    {
        return $this->hasOne(TingkatanKompetisi::className(), ['tingkatan_kompetisi_id' => 'tingkatan_kompetisi_id']);
    }
    public function getStatusKegiatan()
    {
        return $this->hasOne(StatusKegiatan::className(), ['status_kegiatan_id' => 'status_kegiatan_id']);
    }
}

woca/controllers/KompetisiController.php
<?php

namespace backend\modules\woca\controllers;

use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;


use backend\modules\woca\models\search\KompetisiSearch;
use backend\modules\woca\models\Kompetisi;
use backend\modules\woca\models\Dim;
use backend\modules\woca\models\Peserta;
use backend\modules\woca\models\TingkatanKompetisi;
use backend\modules\woca\models\ProposalKompetisiFile;

/**
 * KompetisiController implements the CRUD actions for Kompetisi model.
 */
class KompetisiController extends Controller
{
    public function behaviors()
    {
        return [
            //TODO: crud controller actions are bypassed by default, set the appropriate privilege
            // 'privilege' => [
            //      'class' => \Yii::$app->privilegeControl->getAppPrivilegeControlClass(),
            //      'skipActions' => ['*'],
            //     ],
                
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    public function actionPesertas()
    {
        if(null !== Yii::$app->request->post()){
            $pesertas = Dim::find()->where('deleted!=1')->asArray()->all();
            
            return json_encode($pesertas);
        }else{
            return "Ajax failed";
        }
    }
    public function actionTingkatan()
    {
        if(null !== Yii::$app->request->post()){
            $tingkatan = TingkatanKompetisi::find()->where('deleted!=1')->asArray()->all();
            
            return json_encode($tingkatan);
        }else{
            return "Ajax failed";
        }
    }


    /**
     * Lists all Kompetisi models.
     * @return mixed
     */
    public function actionKompetisiByAdminIndex()
    {
        $searchModel = new KompetisiSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andWhere(['deleted' => 0]);
        $pesertas = Dim::find()->where(['deleted' => 0])->asArray()->all();
        $modelData = Kompetisi::find()->where(['deleted'=> 0])->asArray()->all();
//        $query->leftJoin('table_two','main_table.id = table_two.main_id
//    AND (table_two.something=1 OR table_two.something IS NULL)');
        return $this->render('KompetisiByAdminIndex', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'pesertas' => $pesertas,
            'modelData' => $modelData,
        ]);
    }

    public function actionKompetisiByMahasiswaIndex()
    {
        $searchModel = new KompetisiSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andWhere(['deleted' => 0]);
        $pesertas = Dim::find()->where(['deleted' => 0])->asArray()->all();
        $modelData = Kompetisi::find()->where(['deleted'=> 0])->asArray()->all();
//        $query->leftJoin('table_two','main_table.id = table_two.main_id
//    AND (table_two.something=1 OR table_two.something IS NULL)');
        return $this->render('KompetisiByMahasiswaIndex', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'pesertas' => $pesertas,
            'modelData' => $modelData,
        ]);
    }

    /**
     * Displays a single Kompetisi model.
     * @param integer $id
     * @return mixed
     */
    public function actionKompetisiByMahasiswaView($id)
    {
        return $this->render('KompetisiByMahasiswaView', [
            'model' => $this->findModel($id),
          //  'model_tingkatan_kompetisi' => $model_tingkatan_kompetisi,
        ]);
    }

    public function actionKompetisiByAdminView($id)
    {
        return $this->render('KompetisiByAdminView', [
            'model' => $this->findModel($id),
            //  'model_tingkatan_kompetisi' => $model_tingkatan_kompetisi,
        ]);
    }

    /**
     * Creates a new Kompetisi model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionKompetisiByMahasiswaAdd()
    {
        $ctr=0;
        $model = new Kompetisi();
        $model_tingkatan_kompetisi = TingkatanKompetisi::find()->where(['deleted'=>0])->all();
     //   var_dump($model_tingkatan_kompetisi);
        if ($model->load(Yii::$app->request->post())) {
            $model->save();
            
             $model->filekompetisi = UploadedFile::getInstances($model, 'filekompetisi');
                if($model->filekompetisi != null){ 
                        $modelFile = new ProposalKompetisiFile();

                        $proposal = UploadedFile::getInstance($model,'filekompetisi'); 
                        $proposalname= $proposal->baseName.'.'.$proposal->getExtension();
                       
                        $fileDir = Yii::getAlias('@ProposalKompetisiFilePath').'/'.$proposalname;
                        $modelFile->lokasi_proposal = $fileDir;
                        $modelFile->file_proposal = $proposalname; 
                        $model->save(false);                     
                       
                        $modelFile->deleted = 0;

                        if($modelFile->validate()){ 
                            $proposal->saveAs(Yii::getAlias('@ProposalKompetisiFilePath').'/'.$proposalname);
                            $modelFile->kompetisi_id = $model->kompetisi_id;
                            $modelFile->save();
                        }else{
                           print_r("Error here" );

                            $errors = $modelFile->errors;
                            print_r(array_values($errors));
                            die();
                        }
                 
                }else{
                    print_r("null" );
                }

            foreach(Yii::$app->request->post()['peserta'] as $data){
                // echo "<pre>"; print_r($data); die;
                if($data != "empty"){
                    $ctr++;
                    $peserta = new Peserta();
                    $peserta->kompetisi_id = $model->kompetisi_id;
                    $peserta->dim_id = $data;
                    $peserta->save();   
                }
            }
             
              $model->jumlah_peserta =$ctr;
              $model->save(false);
            return $this->redirect(['kompetisi-by-mahasiswa-view', 'id' => $model->kompetisi_id]);
        } else {
            return $this->render('KompetisiByMahasiswaAdd', [
                'model' => $model,
                'model_tingkatan_kompetisi' => $model_tingkatan_kompetisi,
            ]);
        }
    }

    /**
     * Updates an existing Kompetisi model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionKompetisiByMahasiswaEdit($id)
    {
        $model = $this->findModel($id);
        $model_tingkatan_kompetisi = TingkatanKompetisi::find()->where(['deleted'=>0])->all();
        $modelLampiran = ProposalKompetisiFile::find()->where(['kompetisi_id'=>$model->kompetisi_id])->one();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['kompetisi-by-mahasiswa-view', 'id' => $model->kompetisi_id]);
        } else {
            return $this->render('KompetisiByMahasiswaEdit', [
                'model' => $model,
                'model_tingkatan_kompetisi' => $model_tingkatan_kompetisi,
                'modelLampiran' => $modelLampiran,
            ]);
        }
    }

    /**
     * Deletes an existing Kompetisi model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Kompetisi model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Kompetisi the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Kompetisi::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
  
     
    public function actionDownloadAdmin($id){
        $proposal = ProposalKompetisiFile::find()->where(['kompetisi_id' => $id])->One();
        $path = Yii::getAlias('@ProposalKompetisiFilePath');
        $data = $proposal->file_proposal;
        $file = $path.'\\'.$data;

        if(file_exists($file)){
            Yii::$app->response->sendFile($file);
        }else{
        \Yii::$app->messenger->addErrorFlash("File Tidak Tersedia");
            return $this->redirect(['kompetisi-by-admin-index']);        }
    }

    public function actionDownloadMahasiswa($id){
        $proposal = ProposalKompetisiFile::find()->where(['kompetisi_id' => $id])->One();
        $path = Yii::getAlias('@ProposalKompetisiFilePath');
        $data = $proposal->file_proposal;
        $file = $path.'\\'.$data;

        if(file_exists($file)){
            Yii::$app->response->sendFile($file);
        }else{
        \Yii::$app->messenger->addErrorFlash("File Tidak Tersedia");
            return $this->redirect(['kompetisi-by-mahasiswa-index']);        }
    }

     
    public function actionApproveByAdminIndex($id){
        $model = $this->findModel($id);

        if($model->status_kegiatan_id == 1){
            $model->status_kegiatan_id = 2;
            $model->save();
            \Yii::$app->messenger->addSuccessFlash("Berhasil Approve");
            return $this->redirect('kompetisi-by-admin-index');

woca/views/kompetisi/KompetisiByAdminIndex.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\grid\GridView;
use yii\web\View;
use yii\helpers\Url;
use common\components\ToolsColumn;
use backend\modules\woca\models\ProposalKompetisiFile;
use backend\modules\woca\models\Peserta;
use yii\data\ArrayDataProvider;

/* @var $this yii\web\View */
/* @var $model backend\modules\askm\models\DimPenilaian */

$this->title = 'Kompetisi';
$uiHelper=\Yii::$app->uiHelper;

?>
    <style type="text/css">
        .r{
            margin-left: 450px;
        }

        .marginp{
            margin-top: 20px;
            margin-bottom: 20px;

        .margintp{
            margin-bottom: 15px;
            margin-top: 15px;
        }
        table thead tr{

        }
        tr.header
        {
            cursor:pointer;
        }

        tr.header:hover {
            background: rgba(0,0,0,0.03);
        }

        .header .sign:after{
            content:"\f0d9";
            font-family: FontAwesome;
            font-style: normal;
            font-weight: normal;
            text-decoration: inherit;
        }
        .header.expand .sign:after{
            content:"\f0d7";
            font-family: FontAwesome;
            font-style: normal;
            font-weight: normal;
            text-decoration: inherit;
        }

        .detail{
            display: none;
            background-color: rgba(0,0,0,0.03);
        }

        .detail-first{
        }
    </style>

    <div class="kompetisi-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p class="marginp">

        <?= Html::a('Workshop', ['workshop/index-admin'], ['class' => 'btn btn-info']) ?> &nbsp &nbsp

        <?= Html::a('Kompetisi', ['kompetisi/kompetisi-by-admin-index'], ['class' => 'btn btn-info']) ?> &nbsp &nbsp

        <?= Html::a('Prestasi', ['prestasi/prestasi-by-admin-index'], ['class' => 'btn btn-info']) ?>

        <?= Html::a('Export',['excel'], ['class' => 'btn btn-primary r'])?>
    </p>

    <div class="dim-penilaian-view">

        <?php if(!empty($modelData)){ ?>
            <?= $uiHelper->beginContentRow() ?>
            <?= $uiHelper->beginContentBlock(['id' => 'grid-system3','width' => 12,
                'header' => 'Daftar Kompetisi Mahasiswa',
                'icon' => 'fa fa-bars'
            ]) ?>

            <table class="table">
                <thead>
                <tr>
                    <th style="width:30px;">No</th>
                    <th>Nama kompetisi</th>
                    <th>Tahun</th>
                    <!-- <th>Jumlah peserta</th> -->
                    <th>Penyelenggara</th>
                    <th>Deskripsi</th>
                </tr>
                </thead>
                <tbody>
                <?php
                $no = 1;
                foreach($modelData as $key => $value){
                    $result = null;
                    $file = ProposalKompetisiFile::find()->where(['kompetisi_id' => $value['kompetisi_id']])->all();
                    foreach($file as $data){
                        $result .= $data->file_proposal. "<br>";
                    }


                    echo '<tr class="header expand">';
                    //echo '    <td><button data-id="'.$key.'" class="sign"></button></td>';
                    echo '    <td>'.$no++.'</td>';
                    echo '    <td><a href="#"> '.($value['nama_kompetisi']).' </a></td>';
                    echo '    <td>'.($value['tahun']).'</td>';
                   // echo '    <td>'.$value['tahun'].'</td>';
                    echo '    <td>'.$value['penyelenggara'].'</td>';
                    echo '    <td>'.$value['deskripsi'].'</td>';
//                    echo '    <td>'.$result.'</td>';

                ?>
                    <td><span class="error" style="width:10px;"></span></td>
                <?php

                    echo '</tr>';
                    //echo $no==2?'<tr class="detail-first">':'<tr class="detail">';
                    echo '<tr class="detail">';
                    //echo '    <td></td>';
                    echo '    <td></td>';
                    echo '    <td colspan="11">';
                    echo '    <div class="'.$key.'">';
                    echo '<b>Nama Peserta: </b><br /><br />';
                    $pesertaKompetisi= new ArrayDataProvider([
                        'allModels' => Peserta::find()->where(['kompetisi_id' => $value['kompetisi_id']])->all(),
                        'pagination' => false,
                    ]);
                    $proposalKompetisi= new ArrayDataProvider([
                        'allModels' =>  ProposalKompetisiFile::find()->where(['kompetisi_id' => $value['kompetisi_id']])->all(),
                        'pagination' => false,
                    ]);
//                    $dpKebaikan = new ArrayDataProvider([
//                        'allModels' => $value['kebaikan'],
//                        'pagination' => false,
//                    ]);
                    ?>

                    <?= $uiHelper->beginTab([
                        'icon' => 'fa fa-shield',
                        'tabs' => [
                            ['id' => 'tp_'.$value['kompetisi_id'], 'label' => 'Peserta', 'isActive' => true],
                            ['id' => 'tk_'.$value['kompetisi_id'], 'label' => 'Proposal', 'isActive' => false],
                        ]
                    ]) ?>
                    <?= $uiHelper->beginTabContent(['id'=>'tp_'.$value['kompetisi_id'], 'isActive' => true]) ?>
                    <?= GridView::widget([
                        'dataProvider' => $pesertaKompetisi,
                        'filterModel' => null,
                        'layout' => '{items}',
                        'columns' => [
                            ['class' => 'yii\grid\SerialColumn'],
                            [
                              //  'attribute'=>'nama',
                                'label' => 'Nama',
                                'format' => 'raw',
                                'value'=>  'dim.nama',
                            ],
                        ]
                    ]); ?>
                    <?= $uiHelper->endTabContent() ?>
                    <?= $uiHelper->beginTabContent(['id' => 'tk_'.$value['kompetisi_id'], 'isActive' => false]) ?>
                    <?= GridView::widget([
                        'dataProvider' => $proposalKompetisi,
                        'filterModel' => null,
                        'rowOptions' => function($model){
                            $data = \backend\modules\woca\models\Kompetisi::find()->where(['kompetisi_id' => $model->kompetisi_id])->one();

                            if($data->status_kegiatan_id == 1){
                                return ['class' => 'info'];
                            } else if($data->status_kegiatan_id == 2){
                                return ['class' => 'success'];
                            } else if($data->status_kegiatan_id == 3){
                                return ['class' => 'danger'];
                            } else {
                                return ['class' => 'warning'];
                            }
                        },
                        'layout' => '{items}',
                        'columns' => [
                            ['class' => 'yii\grid\SerialColumn'],
                            [
                                //'attribute' => 'name',
                                'label' => 'File Proposal',
                                'format' => 'raw',
                                'value' => function($model){
                                    $result = null;
                                    $file = ProposalKompetisiFile::find()->where(['kompetisi_id' => $model->kompetisi_id])->all();
                                    foreach($file as $data){
                                        $result .= $data->file_proposal. "<br>";
                                    }

                                    return Html::a($result, ['kompetisi/download-admin', 'id'=>$model->kompetisi_id]);
                                },

                            ],
                            ['class' => 'common\components\ToolsColumn',
                                'template' => '{view} {approve} {reject}',
                                'header' => 'Aksi',

                                'buttons' => [
                                    'view' => function ($url, $model){
                                        $data = \backend\modules\woca\models\Kompetisi::find()->where(['kompetisi_id' => $model->kompetisi_id])->one();
                                        return ToolsColumn::renderCustomButton($url, $data, 'View Detail', 'fa fa-eye');
                                    },
                                    'approve' => function ($url, $model){
                                        $data = \backend\modules\woca\models\Kompetisi::find()->where(['kompetisi_id' => $model->kompetisi_id])->one();
                                        if ($data->status_kegiatan_id == 2 || $data->status_kegiatan_id == 3 || $data->status_kegiatan_id == 4) {
                                            return "";
                                         }else{
                                            return ToolsColumn::renderCustomButton($url, $model, 'Approve', 'fa fa-check');
                                        }
                                    },
                                    'reject' => function ($url, $model){
                                        $data = \backend\modules\woca\models\Kompetisi::find()->where(['kompetisi_id' => $model->kompetisi_id])->one();
                                        if ($data->status_kegiatan_id == 2 || $data->status_kegiatan_id == 3 || $data->status_kegiatan_id == 4) {
                                            return "";
                                        }else{
                                            return ToolsColumn::renderCustomButton($url, $model, 'Reject', 'fa fa-times');
                                        }
                                    },

                                ],
                                'urlCreator' => function ($action, $data, $key, $index){
                                    //     $pegawai = Pegawai::find()->where('deleted != 1')->andWhere(['user_id' => Yii::$app->user->identity->user_id])->one();
                                    if ($action === 'view') {
                                        return Url::toRoute(['kompetisi-by-admin-view', 'id' => $data->kompetisi_id]);
                                    }else if ($action === 'approve') {
                                        return Url::toRoute(['approve-by-admin-index', 'id' => $data->kompetisi_id]);
                                    }else if ($action === 'del') {
                                        return Url::toRoute(['del', 'id' => $key]);
                                    }else if ($action === 'reject') {
                                        return Url::toRoute(['reject-by-admin-index', 'id' => $data->kompetisi_id]);

                                    }
                                }
                            ],


                        ],
                    ]); ?>
                    <?= $uiHelper->endTabContent() ?>
                    <?php
                    echo '</div>';
                    echo '    </td>';
                    echo '</tr>';
                } ?>
                </tbody>
            </table>
            <?=$uiHelper->endContentBlock()?>
            <?=$uiHelper->endContentRow() ?>
        <?php } ?>

        <!-- <?php if(!empty($perilaku_now)){ ?>
    <h1>Nilai Perilaku Tahun Ajaran <?= Html::encode($perilaku_now->ta.'/'.((int)$perilaku_now->ta+1)) ?>, Semester <?= Html::encode($perilaku_now->sem_ta==3?"Pendek":($perilaku_now->sem_ta==2?"Genap":"Gasal")) ?> </h1>
    <?= $uiHelper->renderLine(); ?>
    <?= DetailView::widget([
            'model' => $perilaku_now,
            'attributes' => [
                'akumulasi_skor',
                'nilai_huruf',
                [
                    'label' => 'Bentuk pembinaan',
                    'value' => $perilaku_now->pembinaan,
                ]
            ],
        ]) ?>
    <?php } ?>
    <?php if(!empty($perilaku_history)){ ?>
    <h1>History Nilai Perilaku</h1>
    <?= $uiHelper->renderLine(); ?>
    <table class="tree table">
      <thead>
        <tr>
          <th>Tahun Ajaran</th>
          <th>Semester</th>
          <th>Akumulasi Skor</th>
          <th>Nilai Huruf</th>
        </tr>
      </thead>
      <tbody>
      <?php
            //$insIsExist = false;
            foreach ($perilaku_history as $p) {
                ?>
        <tr>
          <td><?=$p->ta.'/'.((int)$p->ta+1) ?></td>
          <td><?=$p->sem_ta==3?"Pendek":($p->sem_ta==2?"Genap":"Gasal") ?></td>
          <td><?=$p->akumulasi_skor ?></td>
          <td><?=$p->nilai_huruf ?></td>
        </tr>
    <?php } ?>
       </tbody>
    </table>
<?php } ?> -->
    </div>
    </div>

<?php
$this->registerJs("
    $(document).ready(function() {
       $('tr.header').eq(0).toggleClass('expand').nextUntil('tr.header').slideToggle('10');
    });
    $('.header').click(function(){
        $(this).toggleClass('expand').nextUntil('tr.header').slideToggle('10');
    });",
    View::POS_END);
?>

woca/views/kompetisi/KompetisiByMahasiswaAdd.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model backend\modules\woca\models\Kompetisi */

$this->title = 'Tambah Data Kompetisi';
$this->params['breadcrumbs'][] = ['label' => 'Kompetisi', 'url' => ['kompetisi-by-mahasiswa-index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="kompetisi-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_formKompetisi', [
        'model' => $model,
        'model_tingkatan_kompetisi' => $model_tingkatan_kompetisi,
    ]) ?>

</div>

woca/views/kompetisi/KompetisiByMahasiswaView.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use backend\modules\woca\models\Peserta;
use backend\modules\woca\models\ProposalKompetisiFile;
use backend\modules\woca\models\TingkatanKompetisi;

/* @var $this yii\web\View */
/* @var $model backend\modules\woca\models\Kompetisi */

$this->title = $model->nama_kompetisi;
$this->params['breadcrumbs'][] = ['label' => 'Kompetisi', 'url' => ['kompetisi-by-mahasiswa-index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="kompetisi-view">

    <h1><?= Html::encode($this->title) ?></h1>
    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [ 
            'nama_kompetisi',
            'tahun',
            'penyelenggara',
            'deskripsi',
            [
                'label' => 'Tingkatan',
                'value' => function($model){
                    $result = null;
                    $file = TingkatanKompetisi::find()->where(['tingkatan_kompetisi_id' => $model->tingkatan_kompetisi_id])->all();
                    foreach($file as $data){
                        // echo"<pre>"; print_r($data->lokasi->nama_lokasi); die();
                        $result .= $data->tingkatan. "<br>";
                        //$result .= $data->nama . "<br>";
                       // die();
                    }
                       

                    return $result;
                },
                'format' => 'html',
            ],
            [
                //'attribute' => 'name',
                'label' => 'File Proposal',
                'format' => 'raw',
                'value' => function($model){
                    $result = null;
                    $file = ProposalKompetisiFile::find()->where(['kompetisi_id' => $model->kompetisi_id])->all();
                    foreach($file as $data){
                        $result .= $data->file_proposal. "<br>";
                    }

                    return Html::a($result, ['kompetisi/download-admin', 'id'=>$model->kompetisi_id]);
                },

            ],
                'jumlah_peserta',
                [
                    'label' => 'Daftar Peserta',
                    'value' => function($model){
                        $result = null;
                        $peserta = Peserta::find()->where(['kompetisi_id' => $model->kompetisi_id])->all();
                        foreach($peserta as $data){
                            // echo"<pre>"; print_r($data->lokasi->nama_lokasi); die();
                            $result .= $data->dim->nama . "<br>";
                            //$result .= $data->nama . "<br>";
                        }

                        return $result;
                    },
                    'format' => 'html',
                ],

        ],
    ]) ?>

</div>