woca/models/Prestasi.php
<?php

namespace backend\modules\woca\models;

use Yii;

use common\behaviors\TimestampBehavior;
use common\behaviors\BlameableBehavior;
use common\behaviors\DeleteBehavior;

/**
 * This is the model class for table "woca_prestasi".
 *
 * @property integer $prestasi_id
 * @property integer $status_prestasi_id
 * @property string $nama_kompetisi
 * @property string $tahun
 * @property string $pelaksana
 * @property integer $deleted
 * @property string $deleted_at
 * @property string $deleted_by
 * @property string $created_at
 * @property string $created_by
 * @property string $updated_at
 * @property string $updated_by
 *
 * @property WocaRStatusPeserta $statusPrestasi
 * @property WocaSertifikatFile[] $wocaSertifikatFiles
 */
class Prestasi extends \yii\db\ActiveRecord
{

    public $filesertifikat;
    /**
     * behaviour to add created_at and updatet_at field with current datetime (timestamp)
     * and created_by and updated_by field with current user id (blameable)
     */
    public function behaviors(){
        return [
            'timestamp' => [
                'class' => TimestampBehavior::className(),
            ],
            'blameable' => [
                'class' => BlameableBehavior::className(),
            ],
            'delete' => [
                'class' => DeleteBehavior::className(),
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'woca_prestasi';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['tahun'], 'integer'],
        //    [['tahun'], 'berangkatValid'],
            [['tahun','nama_kompetisi','pelaksana','status_prestasi_id'],'required'],
            [['deleted_at', 'created_at', 'updated_at'], 'safe'],
            [['filesertifikat'],'file', 'skipOnEmpty' => true],
            [['nama_kompetisi', 'pelaksana', 'deleted_by', 'created_by', 'updated_by'], 'string', 'max' => 32],
            [['status_prestasi_id'], 'exist', 'skipOnError' => true, 'targetClass' => StatusPeserta::className(), 'targetAttribute' => ['status_prestasi_id' => 'status_prestasi_id']],
            [['status_kegiatan_id'], 'exist', 'skipOnError' => true, 'targetClass' => StatusKegiatan::className(), 'targetAttribute' => ['status_kegiatan_id' => 'status_kegiatan_id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'prestasi_id' => 'Prestasi ID',
            'status_prestasi_id' => 'Status Prestasi',
            'nama_kompetisi' => 'Nama Kompetisi',
            'tahun' => 'Tahun',
            'pelaksana' => 'Pelaksana',
            'filesertifikat' => 'Sertifikat Prestasi',
            'status_kegiatan_id' => 'Status Kegiatan',
            'deleted' => 'Deleted',
            'deleted_at' => 'Deleted At',
            'deleted_by' => 'Deleted By',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
            'updated_at' => 'Updated At',
            'updated_by' => 'Updated By',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStatusPrestasi()
    {
        return $this->hasOne(StatusPeserta::className(), ['status_prestasi_id' => 'status_prestasi_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSertifikatFiles()
    {
        return $this->hasMany(SertifikatFile::className(), ['prestasi_id' => 'prestasi_id']);
    }
    public function getStatusKegiatan()
    {
        return $this->hasOne(StatusKegiatan::className(), ['status_kegiatan_id' => 'status_kegiatan_id']);
    }

}

woca/controllers/PrestasiController.php
<?php

namespace backend\modules\woca\controllers;

use Yii;
use yii\web\Controller;
use yii\web\UploadedFile;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

use backend\modules\woca\models\Prestasi;
use backend\modules\woca\models\search\PrestasiSearch;
use backend\modules\woca\models\StatusPeserta;
use backend\modules\woca\models\SertifikatFile;

/**
 * PrestasiController implements the CRUD actions for Prestasi model.
 */
class PrestasiController extends Controller
{
    public function behaviors()
    {
        return [
            //TODO: crud controller actions are bypassed by default, set the appropriate privilege
            // 'privilege' => [
            //      'class' => \Yii::$app->privilegeControl->getAppPrivilegeControlClass(),
            //      'skipActions' => ['*'],
            //     ],
                
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Prestasi models.
     * @return mixed
     */
    public function actionPrestasiByAdminIndex()
    {
        $searchModel = new PrestasiSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andWhere(['deleted' => 0]);
        //$prestasisiswa = new StatusPeserta::find()->where([$model=>'status_prestasi_id'] = 1);
        $dgrafik = Yii::$app->db->createCommand(
            'SELECT tahun, COUNT(tahun) as jlhperthn FROM woca_prestasi WHERE 
                    status_prestasi_id = 1 OR 
                    status_prestasi_id = 2 OR 
                    status_prestasi_id = 3 OR 
                    status_prestasi_id = 4 OR 
                    status_prestasi_id = 5 
                    GROUP BY tahun'
        )->queryAll();

        return $this->render('PrestasiByAdminIndex', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'dgrafik' => $dgrafik
        ]);
    }


    public function actionPrestasiByMahasiswaIndex()
    {
        $searchModel = new PrestasiSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andWhere(['deleted' => 0]);
        //$prestasisiswa = new StatusPeserta::find()->where([$model=>'status_prestasi_id'] = 1);
        $dgrafik = Yii::$app->db->createCommand(
            'SELECT tahun, COUNT(tahun) as jlhperthn FROM woca_prestasi WHERE 
                    status_prestasi_id = 1 OR 
                    status_prestasi_id = 2 OR 
                    status_prestasi_id = 3 OR 
                    status_prestasi_id = 4 OR 
                    status_prestasi_id = 5 
                    GROUP BY tahun'
        )->queryAll();

        return $this->render('PrestasiByMahasiswaIndex', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'dgrafik' => $dgrafik
        ]);
    }

    /**
     * Displays a single Prestasi model.
     * @param integer $id
     * @return mixed
     */
    public function actionPrestasiByMahasiswaView($id)
    {
        return $this->render('PrestasiByMahasiswaView', [
            'model' => $this->findModel($id),
        ]);
    }
        public function actionPrestasiByAdminView($id)
    {
        return $this->render('PrestasiByAdminView', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Prestasi model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionPrestasiByMahasiswaAdd()
    {
       $model = new Prestasi();
       $model_status_peserta = StatusPeserta::find()->where(['deleted'=>0])->all(); 
 
       // return $arrYears2;

        if ($model->load(Yii::$app->request->post())) {
           
            $model->filesertifikat = UploadedFile::getInstance($model,'filesertifikat');
            if($model->filesertifikat != null){
                $modelFile = new SertifikatFile();
                $sertifikat = UploadedFile::getInstance($model,'filesertifikat');
                $namasertifikat = $sertifikat->baseName.'.'.$sertifikat->getExtension();
                $fileDir = Yii::getAlias('@SertifikatPath').'/'.$namasertifikat;
                $modelFile->lokasi_file = $fileDir;
                $modelFile->sertifikat_file = $namasertifikat ;
                $modelFile->deleted =0;

                $model->save();

                    if($modelFile->validate()){
                        $sertifikat->saveAs($fileDir);
                        $modelFile->prestasi_id = $model->prestasi_id;
                        $modelFile->save(false);
                    }else{
                        print_r("File tidak bisa di validasi");
                    }
            }

            $model->save(false);
            return $this->redirect(['prestasi-by-mahasiswa-view', 'id' => $model->prestasi_id]);
        } else {
            return $this->render('PrestasiByMahasiswaAdd', [
                'model' => $model,
                'model_status_peserta' => $model_status_peserta,
                 
            ]);
        }
    }

    /**
     * Updates an existing Prestasi model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionPrestasiByMahasiswaEdit($id)
    {
        $model = $this->findModel($id);
        $model_status_peserta = StatusPeserta::find()->where(['deleted'=>0])->all();
        $modelLampiran = SertifikatFile::find()->where(['prestasi_id' => $model->prestasi_id])->one();
      //  var_dump($modelLampiran);
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['prestasi-by-mahasiswa-view', 'id' => $model->prestasi_id]);
        } else {
            return $this->render('PrestasiByMahasiswaEdit', [
                'model' => $model,
                'model_status_peserta' => $model_status_peserta,
                'modelLampiran' => $modelLampiran,
            ]);
        }
    }

    /**
     * Deletes an existing Prestasi model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Prestasi model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Prestasi the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Prestasi::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    public function actionDownloadAdmin($id){
        //
        $sertifikat = SertifikatFile::find()->where(['prestasi_id' => $id])->One();
        $path =Yii::getAlias('@SertifikatPath');
        $file = $path.'\\'.$sertifikat->sertifikat_file; 
        
        if(file_exists($file)){
            Yii::$app->response->sendFile($file);
        }else{
             \Yii::$app->messenger->addErrorFlash("File Tidak Tersedia");
            return $this->redirect(['prestasi-by-admin-index']);
        }
    }
        public function actionDownloadMahasiswa($id){
        //
        $sertifikat = SertifikatFile::find()->where(['prestasi_id' => $id])->One();
        $path =Yii::getAlias('@SertifikatPath');
        $file = $path.'\\'.$sertifikat->sertifikat_file; 
        
        if(file_exists($file)){
            Yii::$app->response->sendFile($file);
        }else{
             \Yii::$app->messenger->addErrorFlash("File Tidak Tersedia");
            return $this->redirect(['prestasi-by-mahasiswa-index']);
        }
    }
    public function actionExcel()
    {
        $searchModel = new PrestasiSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('excel', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    public function actionCancelByMahasiswa($id){
        $model = $this->findModel($id);
        if($model->status_kegiatan_id == 1)
        {
            $model->status_kegiatan_id= 4;
            $model->save();

            \Yii::$app->messenger->addSuccessFlash("Berhasil cancel data sertfikat");
            return $this->redirect(['prestasi-by-mahasiswa-index']);
        } else {
            \Yii::$app->messenger->addErrorFlash("Tidak bisa di cancel");
            return $this->render('IndexMahasiswa', [
                'model'=>$model
            ]);
        }
    }
    public function actionApproveByAdminIndex($id){
        $model = $this->findModel($id);

        if($model->status_kegiatan_id == 1){
            $model->status_kegiatan_id = 2;
            $model->save();
            \Yii::$app->messenger->addSuccessFlash("Berhasil Approve");
            return $this->redirect('prestasi-by-admin-index');
        }else{
            \Yii::$app->messenger->addSuccessFlash("Tidak Berhasil Approve");
            return $this->render('PrestasiByAdminIndex');

        }


    }
    public function actionRejectByAdminIndex($id){
        $model = $this->findModel($id);
        if($model->status_kegiatan_id == 1){
            $model->status_kegiatan_id = 3;
            $model->save();
            \Yii::$app->messenger->addSuccessFlash("Workshop berhasil di Reject");

            return $this->redirect('prestasi-by-admin-index');
        }else{
            \Yii::$app->messenger->addErrorFlash("Tidak Berhasil Approve");

woca/views/prestasi/PrestasiByAdminIndex.php
<?php

use common\components\ToolsColumn;
use yii\helpers\Html;
use yii\grid\GridView;
use backend\modules\woca\models\StatusPeserta;
use backend\modules\woca\models\SertifikatFile;
use dosamigos\highcharts\HighCharts;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel backend\modules\woca\models\search\PrestasiSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Prestasi';
$this->params['breadcrumbs'][] = $this->title;
?>

<style type="text/css">
    .CustomClass table thead {
        color:  #3c8dbc;
    }
    .marginp{
        margin-top: 20px;
        margin-bottom: 20px;
    }

    .r{
        margin-left: 450px;
    }

</style>
<div class="prestasi-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>


    <p class="marginp">
        <?= Html::a('Workshop', ['workshop/index-admin'], ['class' => 'btn btn-info']) ?> &nbsp &nbsp

        <?= Html::a('Kompetisi', ['kompetisi/kompetisi-by-admin-index'], ['class' => 'btn btn-info']) ?> &nbsp &nbsp

        <?= Html::a('Prestasi', ['prestasi/prestasi-by-admin-index'], ['class' => 'btn btn-info']) ?>

        <?= Html::a('Export',['excel'], ['class' => 'btn btn-primary r'])?>



    </p>



    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        // 'filterModel' => $searchModel,
        'options' => [
            'class' => 'CustomClass',
        ],
        'rowOptions' => function($model){
            if($model->status_kegiatan_id == 1){
                return ['class' => 'info'];
            } else if($model->status_kegiatan_id == 2){
                return ['class' => 'success'];
            } else if($model->status_kegiatan_id == 3){
                return ['class' => 'danger'];
            } else {
                return ['class' => 'warning'];
            }
        },
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'nama_kompetisi',
            'tahun',
            [
                'label' => 'Pelaksana',
                'value' => 'pelaksana',
            ],

            [
                'label' => 'Pencapaian Prestasi',
                'value' => function($model){
                    $result = null;
                    $statuskompetisi = StatusPeserta::find()->where(['status_prestasi_id' => $model->status_prestasi_id ])->All();
                    //$result = $statuskompetisi->status_prestasi_peserta;
                    foreach($statuskompetisi as $data){
                        $result .= $data->status_prestasi_peserta;
                    }
                    return $result;
                }
            ],
            [
                'label' => 'File Sertifikat',
                'value' => function($model){
                    $result = null;
                    $sertifikat = SertifikatFile::find()->where(['prestasi_id' => $model->prestasi_id])->all();
                    foreach ($sertifikat as $data) {
                        # code...
                        $result .= $data->sertifikat_file;
                    }
                    return Html::a($result,['prestasi/download-admin','id'=>$model->prestasi_id]);
                },
                'format'=>'html'
            ],
            [
                'attribute' => 'status_kegiatan_id',
                'label' => 'Status Permohonan',
                'value' => function($model){
                    if($model->status_kegiatan_id == 1){
                        return "Requested";
                    }elseif($model->status_kegiatan_id == 2){
                        return "Accepted";
                    }elseif ($model->status_kegiatan_id == 3) {
                        return "Rejected";
                    }elseif($model->status_kegiatan_id == 4){
                        return "Canceled";
                    }
                },
            ],
            ['class' => 'common\components\ToolsColumn',
                'template' => '{view} {approve} {reject}',
                'header' => 'Aksi',
                'buttons' => [
                    'view' => function ($url, $model){
                        return ToolsColumn::renderCustomButton($url, $model, 'View Detail', 'fa fa-eye');
                    },
                    'reject' => function ($url, $model){
                        if ($model->status_kegiatan_id == 2 || $model->status_kegiatan_id == 3 || $model->status_kegiatan_id == 4) {
                            return "";
                        }else{
                            return ToolsColumn::renderCustomButton($url, $model, 'Reject', 'fa fa-times');
                        }
                    },
                    'approve' => function ($url, $model){
                        if ($model->status_kegiatan_id == 2 || $model->status_kegiatan_id == 3 || $model->status_kegiatan_id == 4) {
                            return "";


                        }else{
                            return ToolsColumn::renderCustomButton($url, $model, 'Approve', 'fa fa-check');
                        }
                    },

                ],
                'urlCreator' => function ($action, $model, $key, $index){
                    //     $pegawai = Pegawai::find()->where('deleted != 1')->andWhere(['user_id' => Yii::$app->user->identity->user_id])->one();
                    if ($action === 'view') {
                        return Url::toRoute(['prestasi-by-admin-view', 'id' => $key]);
                    }else if ($action === 'approve') {
                        return Url::toRoute(['approve-by-admin-index', 'id' => $model->prestasi_id]);
                    }else if ($action === 'del') {
                        return Url::toRoute(['del', 'id' => $key]);
                    }else if ($action === 'reject') {
                        return Url::toRoute(['reject-by-admin-index', 'id' => $model->prestasi_id]);

                    }
                }
            ],
        ],
    ]); ?>

    <div class="container">
        <div class="row">
            <div class="col-md-8 ">
                <div class="x_panel">
                    <div id="my-chart" style="min-width: 310px; height: 400px; margin-left: : -100 auto">
                        <?php

                        $this->title = 'Prestasi Mahasiswa';

                        foreach ($dgrafik as $values) {
                            # code...
                            // $a[0] = ($values['status_prestasi_id']);
                            // $c[] = ($values['status_prestasi_id']);
                            // $b[] = array('type' => 'column', 'name' => $values['tahun'], 'data' => [array((int)$values['Juara1']), array((int)$values['Juara2']), array((int)$values['Juara3']), array((int)$values['JuaraH1']), array((int)$values['JuaraH2'])]);
                            $b[] = array('type' => 'column',
                                'name' => $values['tahun'], 'data' => array((int)$values['jlhperthn'])
                            );
                        }

                        echo HighCharts::widget([
                            'clientOptions' => [
                                'chart' => [
                                    'type' => 'column'
                                ],
                                'title' => [
                                    'text' => 'Data Prestasi Mahasiswa'
                                ],
                                'xAxis' => [
                                    'categories' => [
                                        '',
                                    ]
                                ],
                                'yAxis' => [
                                    'title' => [
                                        'text' => 'Jumlah Capaian Prestasi per Tahun'
                                    ]
                                ],
                                'series' => $b
                            ]
                        ]);
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

woca/views/prestasi/PrestasiByAdminView.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use backend\modules\woca\models\StatusPeserta;
use backend\modules\woca\models\SertifikatFile;

/* @var $this yii\web\View */
/* @var $model backend\modules\woca\models\Prestasi */

$this->title = $model->nama_kompetisi;
$this->params['breadcrumbs'][] = ['label' => 'Prestasi', 'url' => ['prestasi-by-admin-index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="prestasi-view">

    <h1><?= Html::encode($this->title) ?></h1>


    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            [
                'label' => 'Tingkatan',
                'value' => function($model){
                    $result = null;
                    $statuskompetisi = StatusPeserta::find()->where(['status_prestasi_id' => $model->status_prestasi_id ])->One();
                    $result = $statuskompetisi->status_prestasi_peserta;

                    return $result;
                }
            ],
            [
                'label' => 'File Sertifikat',
                'value' => function($model){
                    $result = null;
                    $sertifikat = SertifikatFile::find()->where(['prestasi_id' => $model->prestasi_id])->all();
                    foreach ($sertifikat as $data) {
                        # code...
                        $result .= $data->sertifikat_file;
                    }
                    return Html::a($result,['prestasi/download-admin','id'=>$model->prestasi_id]);
                },
                'format'=>'html'
            ],
            'nama_kompetisi',
            'tahun',
            'pelaksana',
             
        ],
    ]) ?>

</div>

woca/views/prestasi/PrestasiByMahasiswaIndex.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
use common\components\ToolsColumn;
use backend\modules\woca\models\StatusPeserta;
use backend\modules\woca\models\SertifikatFile;
use dosamigos\highcharts\HighCharts;

/* @var $this yii\web\View */
/* @var $searchModel backend\modules\woca\models\search\PrestasiSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Prestasi';
$this->params['breadcrumbs'][] = $this->title;
?>

<style type="text/css">
  .CustomClass table thead {
   color:  #3c8dbc;
    }
  .marginp{
    margin-top: 20px;
    margin-bottom: 20px;
  }

  .r{
      margin-left: 450px;
  }

</style>
<div class="prestasi-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>


    <p class="marginp">
        <?= Html::a('Workshop', ['workshop/index-mahasiswa'], ['class' => 'btn btn-info']) ?> &nbsp &nbsp

        <?= Html::a('Kompetisi', ['kompetisi/kompetisi-by-mahasiswa-index'], ['class' => 'btn btn-info']) ?> &nbsp &nbsp

        <?= Html::a('Prestasi', ['prestasi/prestasi-by-mahasiswa-index'], ['class' => 'btn btn-info']) ?>

        <?= Html::a('Tambah Prestasi', ['prestasi/prestasi-by-mahasiswa-add'], ['class' => 'btn btn-success r']) ?>
     </p>
    


    <?= GridView::widget([
        'dataProvider' => $dataProvider,
       // 'filterModel' => $searchModel,
        'options' => [
              'class' => 'CustomClass',
         ],
        'rowOptions' => function($model){
            if($model->status_kegiatan_id == 1){
                return ['class' => 'info'];
            } else if($model->status_kegiatan_id == 2){
                return ['class' => 'success'];
            } else if($model->status_kegiatan_id == 3){
                return ['class' => 'danger'];
            } else {
                return ['class' => 'warning'];
            }
        },
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'nama_kompetisi',
            'tahun',
            [
                'label' => 'Pelaksana',
                'value' => 'pelaksana',
            ],
            [
                'label' => 'Pencapaian Prestasi',
                'value' => function($model){
                    $result = null;
                    $statuskompetisi = StatusPeserta::find()->where(['status_prestasi_id' => $model->status_prestasi_id ])->All();
                    foreach ($statuskompetisi as $data){
                        $result .= $data->status_prestasi_peserta;
                    }
                    return $result;
                }
            ],
            [
                'label' => 'File Sertifikat',
                'value' => function($model){
                    $result = null;
                    $sertifikat = SertifikatFile::find()->where(['prestasi_id' => $model->prestasi_id])->all();
                    foreach ($sertifikat as $data) {
                        # code...
                        $result .= $data->sertifikat_file; 
                    }
                    return Html::a($result,['prestasi/download-mahasiswa','id'=>$model->prestasi_id]);
                },
                'format'=>'html'
            ],
            [
                'attribute' => 'status_kegiatan_id',
                'label' => 'Status Permohonan',
                'value' => function($model){
                    if($model->status_kegiatan_id == 1){
                        return "Requested";
                    }elseif($model->status_kegiatan_id == 2){
                        return "Accepted";
                    }elseif ($model->status_kegiatan_id == 3) {
                        return "Rejected";
                    }elseif($model->status_kegiatan_id == 4){
                        return "Canceled";
                    }
                },
            ],
            ['class' => 'common\components\ToolsColumn',
                'template' => '{view} {edit} {cancel}',
                'header' => 'Aksi',
                'buttons' => [
                    'view' => function ($url, $model){
                        return ToolsColumn::renderCustomButton($url, $model, 'View Detail', 'fa fa-eye');
                    },
                    'cancel' => function ($url, $model){
                        if ($model->status_kegiatan_id == 2 || $model->status_kegiatan_id == 3 || $model->status_kegiatan_id == 4) {
                            return "";
                        }else{
                            return ToolsColumn::renderCustomButton($url, $model, 'Cancel', 'fa fa-times');
                        }
                    },
                    'edit' => function ($url, $model){
                        if ($model->status_kegiatan_id == 2 || $model->status_kegiatan_id == 3 || $model->status_kegiatan_id == 4) {
                            return "";
                        } else {
                            return ToolsColumn::renderCustomButton($url, $model, 'Edit', 'fa fa-pencil');
                        }
                    },

                ],
                'urlCreator' => function ($action, $model, $key, $index){
                    if ($action === 'view') {
                        return Url::toRoute(['prestasi-by-mahasiswa-view', 'id' => $key]);
                    }else if ($action === 'edit') {
                        return Url::toRoute(['prestasi-by-mahasiswa-edit', 'id' => $key]);
                    }else if ($action === 'cancel') {
                        return Url::toRoute(['cancel-by-mahasiswa', 'id' => $key]);
                    }
                    // else if($action === 'download'){

                    //     return Url::toRoute(['download', 'id' => $model->laporan_workshop_id]);
                    // }
                }
            ],
         //   ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

    <div class="container">
        <div class="row">
            <div class="col-md-8 ">
                <div class="x_panel">
                    <div id="my-chart" style="min-width: 310px; height: 400px; margin-left: : -100 auto">
                        <?php

                        $this->title = 'Prestasi Mahasiswa';

                        foreach ($dgrafik as $values) {
                            # code...
                            // $a[0] = ($values['status_prestasi_id']);
                            // $c[] = ($values['status_prestasi_id']);
                            // $b[] = array('type' => 'column', 'name' => $values['tahun'], 'data' => [array((int)$values['Juara1']), array((int)$values['Juara2']), array((int)$values['Juara3']), array((int)$values['JuaraH1']), array((int)$values['JuaraH2'])]);
                            $b[] = array('type' => 'column',
                                'name' => $values['tahun'], 'data' => array((int)$values['jlhperthn'])
                            );
                        }

                        echo HighCharts::widget([
                            'clientOptions' => [
                                'chart' => [
                                    'type' => 'column'
                                ],
                                'title' => [
                                    'text' => 'Data Prestasi Mahasiswa'
                                ],
                                'xAxis' => [
                                    'categories' => [
                                        '',
                                    ]
                                ],
                                'yAxis' => [
                                    'title' => [
                                        'text' => 'Jumlah Capaian Prestasi per Tahun'
                                    ]
                                ],
                                'series' => $b
                            ]
                        ]);
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>